# Site settings
title: Nick Restifo
description: Nick Restifo
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nick Restifo
user_description: Hi there, I’m Nick Restifo. I am currently the Manager Of Coaching Analytics for the New York Knicks. I’m a generalist data scientist but I'm particularly interested in predictive modeling. I have a Master's degree in Data Mining and multiple years of NBA front-office experience.
#<br><br> Ocassionally I post smaller projects and thoughts to my new page [here]. The casual version of those and similar thoughts are posted in real-time [here]. <br><br>
#this ^ goes above eventually

user_title: Data Science Leader
email: nick.restifo@protonmail.com
twitter_username: nickrestifo
github_username:  nick-restifo

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
